# Reinforcement Learning

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from matplotlib.colors import ListedColormap
cmap = ListedColormap(['red', 'blue'])

## Value iteration

In [736]:
S1 = 0
S2 = 1
S3 = 2

states = [S1, S2, S3]

A1 = 0
A2 = 1

actions = [A1, A2]

V = np.random.uniform(-1, 1, len(states))
Q = np.random.randn(len(states), len(actions))
gamma = 0.8

P = np.random.uniform(0, 1, size=(len(states), len(actions), len(states)))
P / P.sum(axis=2)[..., None]
r = np.random.uniform(-3, 3, size=(len(states), len(actions)))

P, r, V

(array([[[0.47771845, 0.34999966, 0.95836597],
         [0.65621449, 0.33111871, 0.02016926]],
 
        [[0.0539686 , 0.73936713, 0.43574051],
         [0.38985803, 0.16834621, 0.56604338]],
 
        [[0.63544737, 0.48496635, 0.31428714],
         [0.95576905, 0.45584368, 0.20449484]]]),
 array([[ 1.82857011, -0.10565357],
        [ 0.93149122,  2.7080043 ],
        [ 0.07425485, -2.04037313]]),
 array([ 0.11640284, -0.64767836, -0.72469231]))

In [737]:
while True:
    V_ = np.copy(V)
    for s in states:
        for a in actions:
            Q[s, a] = r[s, a] + gamma * (P[s, a] @ V)
        V[s] = np.max(Q[s])
    
    V = V / V.sum()
    if np.max(np.abs(V - V_)) < 1e-4:
        break

In [738]:
Q, V

(array([[2.28912959, 0.14976342],
        [1.3883834 , 3.62124188],
        [2.72217859, 1.08209239]]),
 array([0.2651742 , 0.41948693, 0.31533887]))

In [766]:
S_facebook = 0
S_class1   = 1
S_class2   = 2
S_class3   = 3
S_sleep    = 4

A_study    = 0
A_facebook = 1
A_sleep    = 2
A_pub      = 3

R = np.array([
    #  A1 A2 A3 A4
    [  0, -1, 0, 0],    # S_facebook 
    [ -2, -1, 0, 0],    # S_class1
    [ -2,  0, 0, 0],    # S_class2
    [ 10,  0, 0, 1],    # S_class3
    [  0,  0, 0, 0]     # S_sleep
])

gamma = 1

P = np.array([
    # S_facebook
    [
        [0, 1, 0, 0, 0],   # A_study
        [1, 0, 0, 0, 0],   # A_facebook
        [0, 1, 0, 0, 0],   # A_sleep
        [0, 1, 0, 0, 0],   # A_pub
    ],
    # S_class1
    [
        [0, 0, 1, 0, 0],   # A_study
        [1, 0, 0, 0, 0],   # A_facebook
        [0, 1, 0, 0, 0],   # A_sleep
        [0, 1, 0, 0, 0],   # A_pub
    ],
    # S_class2
    [
        [0, 0, 0, 1, 0],   # A_study
        [0, 0, 1, 0, 0],   # A_facebook
        [0, 0, 0, 0, 1],   # A_sleep
        [0, 0, 1, 0, 0],   # A_pub
    ],
    # S_class3
    [
        [0, 0, 0, 0, 1],   # A_study
        [0, 0, 0, 1, 0],   # A_facebook
        [0, 0, 0, 1, 0],   # A_sleep
        [0, 0.2, 0.4, 0.4, 0],   # A_pub
    ],
    # S_sleep
    [
        [0, 0, 0, 0, 1],   # A_study
        [0, 0, 0, 0, 1],   # A_facebook
        [0, 0, 0, 0, 1],   # A_sleep
        [0, 0, 0, 0, 1],   # A_pub
    ]
])

V = np.random.uniform(-1, 1, 5)
Q = np.random.randn(5, 4)

In [767]:
while True:
    V_ = np.copy(V)
    for s in states:
        for a in actions:
            Q[s, a] = r[s, a] + gamma * (P[s, a] @ V)
        V[s] = np.max(Q[s])
    
    V = V / V.sum()
    if np.max(np.abs(V - V_)) < 1e-4:
        break

In [773]:
Q, Q.argmax(axis=1), V
# Q[S_class1, A_study]

(array([[ 2.42622452,  0.17678053,  0.02090264,  1.97785161],
        [ 1.05143407,  5.13422882,  1.22592037, -0.13294623],
        [ 0.07424547, -1.92043027,  0.16646628,  1.03040872],
        [-0.20697871,  0.67664511, -0.24400337, -1.93507088],
        [-1.28371123, -0.14703773,  0.06815127, -1.18005021]]),
 array([0, 1, 3, 1, 2], dtype=int64),
 array([ 2.82420246e-01,  5.97640553e-01,  1.19942850e-01, -1.09239976e-06,
        -2.55671477e-06]))

In [764]:
pi = Q.argmax(axis=1)

pi[S_class2]

2

In [ ]:
r = np.array([
    [ 0,  0,  0,  1],
    [ 0, -1, -1, -1],
    [ 0,  0,  0,  0],
])

Q = np.zeros(12, 4)
Q = np.zeros(12, 4)

